import React from 'react'
import Head from 'next/head'

import { Header, Footer } from '../index'

const Layout = ({ children }) => {
  return (
    <div className='container'>
      <Head>
        <title>Web Blog.</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/icons8-icons8.svg' />
      </Head>
      <Header />
      {children}
      <Footer />
    </div>
  )
}

export default Layout
